
env = Environment()
env.PDF('01-problem-solving.tex')
env.PDF('02-algorithm-fundamentals.tex')
env.PDF('03-divide-and-conquer.tex')
env.PDF('04-randomization.tex')
env.PDF('05-heaps-heapsort-sorting-lower-bound.tex')
env.PDF('06-linear-time-sorting-and-selection.tex')
env.PDF('06-hash-tables.tex')
env.PDF('07-amortized-analysis-fibonacci-heaps.tex')
env.PDF('08-max-flow.tex')
env.PDF('09-linear-programming.tex')
env.PDF('10-cg-line-segment-intersection.tex')
env.PDF('11-convex-hull-closest-pair.tex')
env.PDF('12-approximation.tex')
