
env = Environment()
env.PDF('01-problem-solving.tex')
env.PDF('02-algorithm-fundamentals.tex')
env.PDF('03-divide-and-conquer.tex')
env.PDF('04-randomization.tex')
env.PDF('05-linear-time-sorting-and-selection.tex')
env.PDF('06-dynamic-programming-introduction.tex')
#env.PDF('07-max-flow.tex')
#env.PDF('08-max-flow-formulations-and-matching.tex')
#env.PDF('09-linear-programming-and-simplex.tex')
#env.PDF('10-lp-formulations.tex')
#env.PDF('11-cg-and-convex-hulls.tex')
#env.PDF('12-closest-pair.tex')
#env.PDF('13-approximation.tex')
#env.PDF('A1-lp-generalizations.tex')
#env.PDF('A2-cg-line-segment-intersection.tex')
